postgres:
  image: sameersbn/postgresql:9.4-4
  ports:
    - "5432:5432"
  environment:
    - DB_USER=admin
    - DB_PASS=admin
    - DB_NAME=taskapp

app:
  build: .
  ports:
    - "80:80"
  environment:
    - PYTHONPATH=/flask-tasklist
  links:
    - postgres:postgres
